name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}


jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - "5.1.1"
          - "4.14.2"
      fail-fast: false

    name: Ocaml version - ${{ matrix.ocaml-compiler }} - ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup-ocaml
        uses: ocaml/setup-ocaml@master
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: setup
        run: |
          opam install . --deps-only --with-test --yes

      - name: build
        run: opam exec -- dune build

      - name: test
        run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - name: Upload code coverage report
        run: opam exec -- bisect-ppx-report send-to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
